//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFilter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public int id { get; set; }
        public Nullable<int> id_course { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string bienso { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string regid { get; set; }
    }
}
