//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFilter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_online
    {
        public long id { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F13 { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
        public System.Data.Spatial.DbGeography geo { get; set; }
        public string phone_driver { get; set; }
        public string bienso { get; set; }
        public string start { get; set; }
        public string end2 { get; set; }
    }
}
