//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFilter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int id { get; set; }
        public string phone { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string token { get; set; }
        public string uiid { get; set; }
        public Nullable<int> idtaixe { get; set; }
        public string regidkhach { get; set; }
        public string regidtaixe { get; set; }
    }
}
